import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils"
import "./globals.css";

// Components
import ThemeProvider from "@/components/ThemeProvider/ThemeProvider";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
// Fonts
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("grid grid-rows-[auto_1fr_auto] min-h-dvh bg-background font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NavBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>

    </html>
  );
}
